#!/usr/bin/env python3
"""
Generated MCP Server for {{server_title}}

Source: {{source_type}} / {{source_owner}} / {{source_repository}}
Branch: {{source_branch}}
Path: {{source_path}}

This server was generated by API-to-MCP.
"""

from __future__ import annotations

import os
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

try:
    from backend.runtime.dispatcher import ToolDispatcher
except ImportError:
    from runtime.dispatcher import ToolDispatcher

try:
    from backend.runtime.server import create_app as create_runtime_app
except ImportError:
    from runtime.server import create_app as create_runtime_app

MCP_DEFINITION = {{mcp_definition_json}}

TOOLS = {{tools_json}}


class ToolCallRequest(BaseModel):
    tool_name: str = Field(..., min_length=1)
    arguments: dict[str, Any] = Field(default_factory=dict)


def create_app() -> FastAPI:
    base_url = os.getenv("API_BASE_URL")
    default_headers = {}

    api_key = os.getenv("API_KEY")
    if api_key:
        default_headers["X-API-Key"] = api_key

    bearer_token = os.getenv("BEARER_TOKEN")
    if bearer_token:
        default_headers["Authorization"] = f"Bearer {bearer_token}"

    dispatcher = ToolDispatcher(
        mcp_definition=MCP_DEFINITION,
        base_url=base_url,
        default_headers=default_headers if default_headers else None,
    )

    app = FastAPI(
        title=MCP_DEFINITION.get("server", {}).get("title", "{{server_title}}"),
        description=MCP_DEFINITION.get("server", {}).get("description", "{{server_description}}"),
        version=MCP_DEFINITION.get("server", {}).get("api_version", "{{api_version}}"),
    )

    @app.get("/health", tags=["Runtime"])
    async def health() -> dict[str, Any]:
        return {
            "status": "healthy",
            "server": "{{server_name}}",
            "tool_count": len(dispatcher.list_tools()),
        }

    @app.get("/tools", tags=["MCP"])
    async def list_tools() -> dict[str, Any]:
        tools = []
        for tool in dispatcher.list_tools():
            tools.append(
                {
                    "name": tool.get("name"),
                    "description": tool.get("description", ""),
                    "input_schema": tool.get("input_schema", {}),
                    "output_schema": tool.get("output_schema", {}),
                }
            )
        return {"tools": tools, "count": len(tools)}

    @app.post("/tools/call", tags=["MCP"])
    async def call_tool(request: ToolCallRequest) -> dict[str, Any]:
        try:
            return await dispatcher.dispatch(
                tool_name=request.tool_name,
                arguments=request.arguments,
            )
        except Exception as exc:
            raise HTTPException(status_code=500, detail=str(exc)) from exc

    @app.get("/", tags=["Runtime"])
    async def root() -> dict[str, Any]:
        return {
            "name": "{{server_name}}",
            "description": "{{server_description}}",
            "tools": len(dispatcher.list_tools()),
            "health": "/health",
            "tool_list": "/tools",
            "tool_call": "/tools/call",
        }

    return app


app = create_app()

if __name__ == "__main__":
    import uvicorn

    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "3000"))

    uvicorn.run(app, host=host, port=port)